# Generated by Django 5.0.1 on 2024-02-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidamount', models.BigIntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bidding',
                'verbose_name_plural': 'Bidding',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'contactus',
                'verbose_name_plural': 'ContactUs',
            },
        ),
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='talkdesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('subject', models.TextField()),
            ],
            options={
                'verbose_name': 'talkdesigner',
                'verbose_name_plural': 'TalkDesigner',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('User', 'User'), ('Designer', 'Designer')], max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('totalamount', models.BigIntegerField()),
                ('booking_amt', models.BigIntegerField()),
                ('mode', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.bidding')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField(auto_now=True)),
                ('mode', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='aspecthomesapp.booking')),
                ('u_id', models.ForeignKey(db_column='ut_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pay_user_type', to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perferredstyle', models.ImageField(upload_to='userstyleimage')),
                ('description', models.TextField()),
                ('submittime', models.TimeField(auto_now=True)),
                ('budget', models.BigIntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'requirement',
                'verbose_name_plural': 'Requirement',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ImageField(upload_to='project')),
                ('description', models.CharField(max_length=100)),
                ('u_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to='aspecthomesapp.user')),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_name', to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('submissiondate', models.DateField(auto_now=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.BigIntegerField()),
                ('profile_pic', models.ImageField(upload_to='Profilepic')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=15)),
                ('work_exp', models.IntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'Detail',
            },
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
                ('expirydate', models.DateField()),
                ('transaction_id', models.BigIntegerField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='aspecthomesapp.booking')),
                ('p_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modeofpayment', to='aspecthomesapp.payment')),
                ('u_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card_user_type', to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'Card',
            },
        ),
        migrations.AddField(
            model_name='bidding',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user'),
        ),
        migrations.CreateModel(
            name='virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageupload', models.ImageField(upload_to='360')),
                ('description', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'virtual',
                'verbose_name_plural': 'Virtual',
            },
        ),
        migrations.AddField(
            model_name='bidding',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.virtual'),
        ),
    ]
