# Generated by Django 5.0.1 on 2024-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0002_requirement_virtual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='perferredstyle',
            new_name='preferredstyle',
        ),
    ]
