# Generated by Django 5.0.1 on 2024-02-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0003_rename_perferredstyle_requirement_preferredstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='budget',
            field=models.FloatField(),
        ),
    ]
