# Generated by Django 5.0.1 on 2024-02-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0005_remove_bidding_v_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_bids', to='aspecthomesapp.user'),
        ),
    ]
