# Generated by Django 5.0.1 on 2024-02-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0006_bidding_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='requirementid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.requirement'),
        ),
    ]
