# Generated by Django 5.0.1 on 2024-02-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0007_bidding_requirementid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='designer',
        ),
    ]
