# Generated by Django 5.0.1 on 2024-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0012_alter_bidding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_amt',
        ),
    ]
