# Generated by Django 5.0.1 on 2024-02-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0013_remove_booking_booking_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='v_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='designerdate',
            field=models.DateField(null=True),
        ),
    ]
