# Generated by Django 5.0.1 on 2024-03-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0015_remove_booking_designerdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
