# Generated by Django 5.0.1 on 2024-03-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0016_remove_booking_mode_remove_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='p_id',
        ),
        migrations.AddField(
            model_name='card',
            name='cname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expirymonth',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.booking'),
        ),
        migrations.AlterField(
            model_name='card',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expirydate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='b_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.booking'),
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemail', models.EmailField(max_length=254)),
                ('caddress', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='aspecthomesapp.booking')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspecthomesapp.user')),
            ],
            options={
                'verbose_name': 'billing',
                'verbose_name_plural': 'Billing',
            },
        ),
    ]
