# Generated by Django 5.0.1 on 2024-03-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0017_remove_card_p_id_card_cname_card_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='cname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
