# Generated by Django 5.0.1 on 2024-03-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0019_billing_dname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='u_id',
        ),
    ]
