# Generated by Django 5.0.1 on 2024-03-03 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0020_remove_card_booking_id_remove_card_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bid_id',
            new_name='bid',
        ),
    ]
