# Generated by Django 5.0.1 on 2024-03-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0021_rename_bid_id_booking_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expirymonth',
        ),
    ]
