# Generated by Django 5.0.1 on 2024-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0022_remove_card_expirymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirydate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
