# Generated by Django 5.0.1 on 2024-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0025_alter_card_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='transaction_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
