# Generated by Django 5.0.1 on 2024-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspecthomesapp', '0026_alter_card_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
